export const ROUTES_MOCK = {
  LOGIN: "/login",
  INVENTORY: "/inventario",
  PRODUCTS: "/productos",
  BRANDS: "/marcas",
  CATEGORIES: "/categorias",
  WAREHOUSES: "/almacenes",
  PURCHASE_ORDERS: "/compras",
  NEW_PURCHASE_ORDER: "/nueva-compra",
  EDIT_PURCHASE_ORDER: "/editar-compra",
  PROVIDERS: "/proveedores",
  SALE_ORDERS: "/ventas",
  NEW_SALE_ORDER: "/nueva-venta",
  EDIT_SALE_ORDER: "/editar-venta",
  SALE_PAYMENT: "/pagos",
  CLIENTS: "/clientes",
  REPORTS: "/reportes",
  USERS: "/usuarios",
  ROLES: "/roles",
  DASHBOARD: "/dashboard",
};
